### PR TITLE
Allow to sync only future events

### PR DESCRIPTION
**Pull request by rufuswilson**
Only sync future events
All events ending before the beginning of the day when the script is run will be deleted from the calendar

### CODE REVIEW

**Comment by rufuswilson** [comment]
Yes, deleting past events was my initial idea.

Oh OK, I see. If we keep past recurring events? or not delete past events?

**Comment by jonas0b1011001** [comment]
> Yes, deleting past events was my initial idea.
In that case you have to move your if statement to the beginning of the foreach function, as it currently will never be reached unless the event gets changed (which is unlikely to happen for past events)

> Oh OK, I see. If we keep past recurring events? or not delete past events?
Ignoring recurring events will probably work, but create a really unintuitive behavior. For users that have never seen the code there will be no easy explanation why some past events are showing while other are not added to the calendar.

**Comment by rufuswilson** [comment]
> In that case you have to move your if statement to the beginning of the foreach function, as it currently will never be reached unless the event gets changed (which is unlikely to happen for past events)

Good call

> Ignoring recurring events will probably work, but create a really unintuitive behavior. For users that have never seen the code there will be no easy explanation why some past events are showing while other are not added to the calendar.

OK so let's drop this feature then

**Comment by jonas0b1011001** [comment]
We don't have to drop it completely but it will take more effort to get it to work completely.

I played around a bit and came up with the following code which will get rid of past instances of a recurring event by setting the initial start date to the first occurence in the future.
```
var recur = event.getFirstPropertyValue('rrule');
var dtstart = event.getFirstPropertyValue('dtstart');
var iter = recur.iterator(dtstart);
var rngSearch = new ICAL.Time.fromJSDate(new Date());
var newStartDate;
for (var next = iter.next(); next; next = iter.next()) {
  if (next.compare(rngSearch) < 0) {
    continue;
  }
  newStartDate = next;
  break;
}
if (newStartDate != null){
  var diff = newStartDate.subtractDate(icalEvent.startDate);
  icalEvent.endDate.addDuration(diff);
  icalEvent.startDate = newStartDate;
}
```

**Comment by jonas0b1011001** [comment]
I created a separate [branch](https://github.com/jonas0b1011001/GAS-ICS-Sync-CalAPIv3/tree/sync-only-future-events) for easier testing and to incorporate code refractoring done in the main branch.
The code in the branch seems to work fine for normal events and edits recurring events as described in an earlier comment.
However before this can be added to the Main branch we have to take care of events with recurrence-id. These events alter instances of a recurring event and can reschedule an instance that is initially scheduled in the future to have already taken place in the past and vice versa.

**Comment by rufuswilson** [comment]
Would you have an example of events with recurrence-id?
I have never encountered them before.

**Comment by jonas0b1011001** [comment]
This [one](https://pastebin.com/raw/XmpqVjKn) has one event that defines a recurring event series. The other six events are each modifing one of the instances to take place at a different time than defined by the RRULE.

**Pull request closed without merging**
